project:
  type: website

website:
  title: "Ward Eiling"
  navbar:
    left:
      - href: index.qmd
        text: "About Me"
      - href: mywork.qmd
        text: "My Work"
      - href: resume.pdf
        text: "Resume"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



